name: Build and Publish Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      packages: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set lowercase repository name
        id: vars
        run: echo "REPOSITORY_NAME=$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPOSITORY_NAME }}:latest
            ghcr.io/${{ env.REPOSITORY_NAME }}:${{ github.run_number }}

      - name: Clean up Docker environment
        run: docker system prune -af
